apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: webshop-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: webshop-1
    app.kubernetes.io/part-of: dc-metro-map-app
  name: webshop-1
  namespace: rh-ee-jbergfel
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: webshop-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: webshop-1
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:rh-ee-jbergfel-webshop-1
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
