apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: webshop-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: webshop-1
    app.kubernetes.io/part-of: dc-metro-map-app
  name: webshop-1
  namespace: rh-ee-jbergfel
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: webshop-1
    weight: 100
status: {}
