apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    build.appstudio.openshift.io/application: dc-metro-map-app
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/component: webshop-3
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: webshop-3
  namespace: rh-ee-jbergfel
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: webshop-3
status:
  configuration:
    generatedName: ""
