apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-1
    app.kubernetes.io/part-of: dc-metro-map-app
  name: python-1
  namespace: rh-ee-jbergfel
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: python-1
status:
  loadBalancer: {}
