apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: webshop-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: webshop-3
    app.kubernetes.io/part-of: dc-metro-map-app
  name: webshop-3
  namespace: rh-ee-jbergfel
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: webshop-3
status:
  loadBalancer: {}
