apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nodejs
  namespace: rh-ee-jbergfel
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:2483d4126e85acac5e6e3ab85b752fdc30ed5fbeebccc1436fc144f38ab85e65
        name: container-image
        resources: {}
status: {}
