apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python
  namespace: rh-ee-jbergfel
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:rh-ee-jbergfel-python
        name: container-image
        resources: {}
status: {}
